version: '3.6'

volumes:
  mysql:

services:
  apache:
    build:
      dockerfile: Dockerfile.apache
      context: .
    depends_on:
      - mysql
    volumes:
      - ./files:/var/www/web/sites/default/files
    labels:
      - "traefik.frontend.rule=Host:${D_HOST}"
      - "traefik.docker.network=traefik"
    working_dir: /var/www/web
    environment:
      - DOCUMENT_ROOT=/var/www/web
      - DRUSH_OPTIONS_URI=http://${D_HOST}
    env_file:
      - .env
    networks:
      - traefik
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - mysql:/var/lib/mysql
      - ./configs/mysql/dev-my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER:     ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  pma:
    image: nazarpc/phpmyadmin
    depends_on:
      - mysql
    labels:
      - "traefik.frontend.rule=Host:pma.${D_HOST}"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - default


networks:
  default:
  traefik:
    external:
      name: traefik
