version: '3.6'

volumes:
  mysql:

services:
  php-dev:
    image: droptica/php-cli:${D_PHP_VERSION}
    depends_on:
      - mysql
    working_dir: /app/drupal
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - COMPOSER_PATH=/app/app
      - PHP_MEMORY_LIMIT=-1
      - DRUSH_OPTIONS_URI=http://${D_HOST}

  apache:
    image: droptica/php-apache:${D_PHP_VERSION}
    depends_on:
      - mysql
    volumes:
      - ./drupal:/var/www
    labels:
      - "traefik.frontend.rule=Host:${D_HOST}"
      - "traefik.docker.network=traefik"
    working_dir: /var/www/web
    environment:
      - DOCUMENT_ROOT=/var/www/web
    env_file:
      - .env
    networks:
      - traefik
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - mysql:/var/lib/mysql
      - ./configs/mysql/dev-my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER:     ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  pma:
    image: nazarpc/phpmyadmin
    depends_on:
      - mysql
    labels:
      - "traefik.frontend.rule=Host:pma.${D_HOST}"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - default

  mailcatcher:
    image: droptica/mailcatcher
    labels:
      - "traefik.frontend.rule=Host:mails.${D_HOST}"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - default

  gulp:
    image: droptica/gulp:${D_NODE_VERSION}
    env_file:
      - .env
    volumes:
      - ./drupal:/app
    working_dir: /app

networks:
  default:
  traefik:
    external:
      name: traefik
