version: '3.5'

services:
  traefik:
    container_name: traefik
    restart: always
    image: traefik:1.7
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - 80:80
      - 443:443
      - 8080:8080 # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./config/traefik.dev.toml:/etc/traefik/traefik.toml
      - ./config/ssl:/etc/traefik/ssl
    networks:
      - traefik

networks:
  traefik:
    name: traefik
